# Resources/config/controllers.yml
services:

    WBW\Bundle\EDMBundle\Controller\DocumentController:
        alias:  "wbw.edm.controller.document"
        public: true

    WBW\Bundle\EDMBundle\Controller\DropzoneController:
        alias:  "wbw.edm.controller.dropzone"
        public: true

    wbw.edm.controller.document:
        class: WBW\Bundle\EDMBundle\Controller\DocumentController
        calls:
            - [ "setContainer", [ "@service_container" ] ]

    wbw.edm.controller.dropzone:
        class: WBW\Bundle\EDMBundle\Controller\DropzoneController
        calls:
            - [ "setContainer", [ "@service_container" ] ]
