# Resources/config/controllers.yml
services:

    WBW\Bundle\EDMBundle\Controller\DocumentController:
        alias: "wbw.edm.controller.document"

    wbw.edm.controller.document:
        class:  WBW\Bundle\EDMBundle\Controller\DocumentController
        public: true
        calls:
            - [ "setContainer", [ "@service_container" ] ]

    WBW\Bundle\EDMBundle\Controller\DropzoneController:
        alias: "wbw.edm.controller.dropzone"

    wbw.edm.controller.dropzone:
        class:  WBW\Bundle\EDMBundle\Controller\DropzoneController
        public: true
        calls:
            - [ "setContainer", [ "@service_container" ] ]
