# Resources/config/datatables.yml
services:

    wbw.edm.datatables.provider.document:
        class:  WBW\Bundle\EDMBundle\DataTables\Provider\DocumentDataTablesProvider
        public: true
        arguments: [ "@router", "@translator", "@wbw.bootstrap.twig.extension.css.button" ]
        calls:
            - [ "setDocumentIconProvider", [ "@wbw.edm.provider.document_icon" ] ]
            - [ "setKernelEventListener",  [ "@wbw.core.event_listener.kernel" ] ]
        tags:
            - { name: "wbw.jquery.datatables.provider" }
