# Resources/config/services.yml
services:

    wbw.edm.event_listener.document:
        class:     WBW\Bundle\EDMBundle\EventListener\DocumentEventListener
        arguments: ["@doctrine.orm.entity_manager", "@wbw.edm.manager.storage"]
        public:    true
        tags:
            - { name: "kernel.event_listener", event: "wbw.edm.event.directory.delete",   method: "onDeletedDirectory" }
            - { name: "kernel.event_listener", event: "wbw.edm.event.directory.download", method: "onDownloadedDocument" }
            - { name: "kernel.event_listener", event: "wbw.edm.event.directory.move",     method: "onMovedDocument" }
            - { name: "kernel.event_listener", event: "wbw.edm.event.directory.new",      method: "onNewDirectory" }
            - { name: "kernel.event_listener", event: "wbw.edm.event.document.delete",    method: "onDeletedDocument" }
            - { name: "kernel.event_listener", event: "wbw.edm.event.document.download",  method: "onDownloadedDocument" }
            - { name: "kernel.event_listener", event: "wbw.edm.event.document.move",      method: "onMovedDocument" }
            - { name: "kernel.event_listener", event: "wbw.edm.event.document.upload",    method: "onUploadedDocument" }
