# Resources/config/routing.yml
edm_directory:
    resource: "@EDMBundle/Resources/config/routing/directory.yml"
    prefix:   "/"

edm_document:
    resource: "@EDMBundle/Resources/config/routing/document.yml"
    prefix:   "/"

edm_dropzone:
    resource: "@EDMBundle/Resources/config/routing/dropzone.yml"
    prefix:   "/"
