# Resources/config/routing.yml
wbw_edm_document:
    resource: "@WBWEDMBundle/Resources/config/routing/document.yml"
    prefix:   "/edm"

wbw_edm_dropzone:
    resource: "@WBWEDMBundle/Resources/config/routing/dropzone.yml"
    prefix:   "/edm"
