# Resources/config/services.yml
services:

    wbw.edm.manager.storage:
        class:  WBW\Bundle\EDMBundle\Manager\StorageManager
        arguments: [ "@logger" ]
        public: true

    wbw.edm.provider.document_icon:
        class:  WBW\Bundle\EDMBundle\Provider\DocumentIconProvider
        public: true
