# Resources/config/twig.yml
services:

    wbw.edm.twig.extension.edm:
        class:     WBW\Bundle\EDMBundle\Twig\Extension\EDMTwigExtension
        arguments: ["@router", "@translator"]
        public:    true
        tags:
            - { name: "twig.extension" }
