# .travis.yml
language: "php"

php:
    - "5.6"
    - "7.0"
    - "7.1"
    - "7.2"
    - "nightly"
    - "hhvm"

matrix:
    include:
        - php: "5.6"
          env: "SYMFONY_VERSION=2.8.*"
        - php: "5.6"
          env: "SYMFONY_VERSION=3.0.*"
        - php: "5.6"
          env: "SYMFONY_VERSION=3.1.*"
        - php: "5.6"
          env: "SYMFONY_VERSION=3.2.*"
        - php: "5.6"
          env: "SYMFONY_VERSION=3.3.*"
        - php: "5.6"
          env: "SYMFONY_VERSION=3.4.*"
        - php: "7.1"
          env: "SYMFONY_VERSION=4.0.*"
        - php: "7.1"
          env: "SYMFONY_VERSION=4.1.*"
    allow_failures:
        - php: "nightly"
        - php: "hhvm"

before_install:
    - if [ "$TRAVIS_PHP_VERSION" != "hhvm" ]; then echo "memory_limit=3072M" >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini; fi;
    - if [ "$SYMFONY_VERSION" != "" ]; then composer require "symfony/symfony:${SYMFONY_VERSION}" --no-update; else composer require "symfony/symfony:3.4.*"; fi;
    - if [ "$SYMFONY_VERSION" = "3.4.*@dev" ]; then perl -pi -e 's/^}$/,"minimum-stability":"dev"}/' composer.json; fi;

install:
    - "composer update"
    - "wget -c -nc --retry-connrefused --tries=0 https://github.com/php-coveralls/php-coveralls/releases/download/v2.0.0/php-coveralls.phar -O coveralls.phar"
    - "chmod +x coveralls.phar"
    - "php coveralls.phar --version"

before_script:
    - "mkdir -p build/logs"

script:
    - "vendor/bin/phpunit --coverage-clover build/logs/clover.xml"
    - "cat Tests/Fixtures/app/var/logs/test.log"

after_success:
    - "php coveralls.phar -v"

notifications:
    email:
        on_failure: "always"
        on_success: "always"
