# Resources/config/datatables.yml
services:

    wbw.edm.datatables.provider.document:
        class:  WBW\Bundle\EDMBundle\DataTables\Provider\DocumentDataTablesProvider
        public: true
        arguments: [ "@translator", "@router", "@wbw.bootstrap.twig.extension.component.button" ]
        calls:
            - [ "setDocumentIconProvider", [ "@wbw.edm.provider.document_icon" ] ]
        tags:
            - { name: "kernel.event_listener", event: "kernel.request",   method: "onKernelRequest" }
            - { name: "wbw.datatables.provider" }
