# Resources/config/routing.yml
wbw_edm_document:
    prefix:   "/"
    resource: "@WBWEDMBundle/Resources/config/routing/document.yml"

wbw_edm_dropzone:
    prefix:   "/"
    resource: "@WBWEDMBundle/Resources/config/routing/dropzone.yml"
