# Resources/config/routing/directory.yml
edm_directory_delete:
    path:     "/directory/delete/{id}"
    defaults: { _controller: "EDMBundle:Document:delete" }
    methods:  ["GET"]

edm_directory_download:
    path:     "/directory/download/{id}"
    defaults: { _controller: "EDMBundle:Document:download" }
    methods:  ["GET"]

edm_directory_edit:
    path:     "/directory/edit/{id}"
    defaults: { _controller: "EDMBundle:Document:edit" }
    methods:  ["GET", "POST"]

edm_directory_move:
    path:     "/directory/move/{id}"
    defaults: { _controller: "EDMBundle:Document:move" }
    methods:  ["GET", "POST"]

edm_directory_new:
    path:     "/directory/new/{id}"
    defaults: { _controller: "EDMBundle:Document:new", id: null }
    methods:  ["GET", "POST"]

edm_directory_open:
    path:     "/directory/open/{id}"
    defaults: { _controller: "EDMBundle:Document:open", id: null }
    methods:  ["GET"]
