# Resources/config/routing/dropzone.yml
wbw_edm_dropzone_index:
    path: "/dropzone/index/{id}"
    defaults: { _controller: "WBW\\Bundle\\EDMBundle\\Controller\\DropzoneController:indexAction", id: null }
    methods: [ "GET" ]

wbw_edm_dropzone_serialize:
    path: "/dropzone/serialize/{id}"
    defaults: { _controller: "WBW\\Bundle\\EDMBundle\\Controller\\DropzoneController:serializeAction", id: null }
    methods: [ "GET", "POST" ]

wbw_edm_dropzone_upload:
    path: "/dropzone/upload/{id}"
    defaults: { _controller: "WBW\\Bundle\\EDMBundle\\Controller\\DropzoneController:uploadAction", id: null }
    methods: [ "GET", "POST" ]
