# Resources/config/routing/dropzone.yml
wbw_edm_dropzone_index:
    path:     "/dropzone/index/{id}"
    defaults: { _controller: "WBWEDMBundle:Dropzone:index", id: null}
    methods:  ["GET"]

wbw_edm_dropzone_upload:
    path:     "/dropzone/upload/{id}"
    defaults: { _controller: "WBWEDMBundle:Dropzone:upload", id: null}
    methods:  ["GET", "POST"]

wbw_edm_dropzone_show:
    path:     "/dropzone/show/{id}"
    defaults: { _controller: "WBWEDMBundle:Dropzone:show", id: null}
    methods:  ["GET", "POST"]
